services:
  ytfinall:
    image: ghcr.io/jnracreates/ytfinall:latest
    # To build from source instead, comment out the line above and uncomment:
    # build: .
    container_name: ytfinall
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MEDIA_PATH}:/media/users
      - ${APP_DATA_PATH}:/app-data
      - ${CONFIG_PATH}:/config
      - ${JELLYFIN_CONFIG_PATH}:/jellyfin-config
    ports:
      - "6842:6842"
    restart: unless-stopped
